team = [
 ("Debra Capini","Arquero",59,"Portugal"),
 ("Pablo Gonzalez","Delantero",90,"Argentina"),
 ("Hin guin","Aguatero",73,"China"),
 ("Sena Aronson","Delantero",11,"Irlanda"),
 ("Laney Rembrandt","Defensor",10,"Alemania"),
 ("Fernande Gallelli","Mediocampista",62,"España"),
 ("Amery Darey","Arquero",27,"Inglaterra"),
 ("Facundo Aguinaga","Arquero",15,"Argentina"),
 ("Augusto Pulgar","Arquero",69,"Chile"),
 ("Britte Brocks","Defensor",92,"EEUU"),
 ("Rob Issard","Arquero",59,"Canada"),
 ("Susanne Manifould","Delantero",39,"Suecia"),
 ("Elvis Rodriguez","Delantero",80,"Colombia"),
 ("Roman Riquelme","Aguatero",43,"Argentina"),
 ("Genghis Khan","Delantero",861,"Mongolia"),
 ("Baxy Pex","Arquero",37,"Rumania"),
 ("Harriet Elsworth","Delantero",78,"Escocia"),
 ("Robert Downey Jr","Arquero",10,"Paraguay"),
 ("Tomas Maure","Mediocampista",15,"Argentina"),
 ("Tandie Stuttard","Arquero",8,"Filipinas"),
 ("Aldous Menier","Arquero",90,"China"),
 ("Chrysler Skiplorne","Delantero",30,"Inglaterra"),
 ("Salomu Emtiti","Delantero",25,"Nigeria"),
 ("Rudolph Stollberg","Defensor",18,"Inglaterra"),
 ("Marsh Marsh","Arquero",19,"Egipto")
]

